
# Addresses del stack Pi-Plates
RELAY_PLATE_1_ADDRESS = 0
RELAY_PLATE_2_ADDRESS = 1
THERMO_PLATE_ADDRESS = 2
ADC_PLATE_ADDRESS = 3

# Relés: (address, relay). El relay 2 del address 0 queda libre porque el Water
# Level Solenoid fue excluido por requisito del proyecto.
AIR_COMPRESSOR_RELAY = (RELAY_PLATE_1_ADDRESS, 1)
MAGNETIC_BOOSTER_PUMP_RELAY = (RELAY_PLATE_1_ADDRESS, 3)
COOLING_TRAP_A_RELAY = (RELAY_PLATE_1_ADDRESS, 4)
COOLING_TRAP_B_RELAY = (RELAY_PLATE_1_ADDRESS, 5)
DIFFUSE_VALVE_A_RELAY = (RELAY_PLATE_1_ADDRESS, 6)
DIFFUSE_VALVE_B_RELAY = (RELAY_PLATE_1_ADDRESS, 7)
CHAMBER_VALVE_A_RELAY = (RELAY_PLATE_1_ADDRESS, 8)
CHAMBER_VALVE_B_RELAY = (RELAY_PLATE_2_ADDRESS, 1)
MECHANICAL_PUMP_A_RELAY = (RELAY_PLATE_2_ADDRESS, 2)
MECHANICAL_PUMP_B_RELAY = (RELAY_PLATE_2_ADDRESS, 3)
DIFFUSION_PUMP_A_RELAY = (RELAY_PLATE_2_ADDRESS, 4)
DIFFUSION_PUMP_B_RELAY = (RELAY_PLATE_2_ADDRESS, 5)
GATE_VALVE_A_RELAY = (RELAY_PLATE_2_ADDRESS, 6)
GATE_VALVE_B_RELAY = (RELAY_PLATE_2_ADDRESS, 7)
MICROWAVE_COOLING_RELAY = (RELAY_PLATE_2_ADDRESS, 8)

RELAYS = {
    "Air Compressor": AIR_COMPRESSOR_RELAY,
    "Magnetic Booster Pump": MAGNETIC_BOOSTER_PUMP_RELAY,
    "Cooling Trap A": COOLING_TRAP_A_RELAY,
    "Cooling Trap B": COOLING_TRAP_B_RELAY,
    "Diffuse Valve A": DIFFUSE_VALVE_A_RELAY,
    "Diffuse Valve B": DIFFUSE_VALVE_B_RELAY,
    "Chamber Valve A": CHAMBER_VALVE_A_RELAY,
    "Chamber Valve B": CHAMBER_VALVE_B_RELAY,
    "Mechanical Pump A": MECHANICAL_PUMP_A_RELAY,
    "Mechanical Pump B": MECHANICAL_PUMP_B_RELAY,
    "Diffusion Pump A": DIFFUSION_PUMP_A_RELAY,
    "Diffusion Pump B": DIFFUSION_PUMP_B_RELAY,
    "Gate Valve A": GATE_VALVE_A_RELAY,
    "Gate Valve B": GATE_VALVE_B_RELAY,
    "Microwave Cooling": MICROWAVE_COOLING_RELAY,
}