"""Variables configurables para startup process 2.0.

Cambie solamente este archivo para ajustar tiempos, límites, simulación y
asignaciones de hardware.
"""

# Modos de operación
AUTOMATIC_MODE = False
SIMULATE_SENSOR_DATA = True

# Addresses del stack Pi-Plates
RELAY_PLATE_1_ADDRESS = 0
RELAY_PLATE_2_ADDRESS = 1
THERMO_PLATE_ADDRESS = 2
ADC_PLATE_ADDRESS = 3

# Relés: (address, relay). El relay 2 del address 0 queda libre porque el Water
# Level Solenoid fue excluido por requisito del proyecto.
AIR_COMPRESSOR_RELAY = (RELAY_PLATE_1_ADDRESS, 1)
MAGNETIC_BOOSTER_PUMP_RELAY = (RELAY_PLATE_1_ADDRESS, 3)
COOLING_TRAP_A_RELAY = (RELAY_PLATE_1_ADDRESS, 4)
COOLING_TRAP_B_RELAY = (RELAY_PLATE_1_ADDRESS, 5)
DIFFUSE_VALVE_A_RELAY = (RELAY_PLATE_1_ADDRESS, 6)
DIFFUSE_VALVE_B_RELAY = (RELAY_PLATE_1_ADDRESS, 7)
CHAMBER_VALVE_A_RELAY = (RELAY_PLATE_1_ADDRESS, 8)
CHAMBER_VALVE_B_RELAY = (RELAY_PLATE_2_ADDRESS, 1)
MECHANICAL_PUMP_A_RELAY = (RELAY_PLATE_2_ADDRESS, 2)
MECHANICAL_PUMP_B_RELAY = (RELAY_PLATE_2_ADDRESS, 3)
DIFFUSION_PUMP_A_RELAY = (RELAY_PLATE_2_ADDRESS, 4)
DIFFUSION_PUMP_B_RELAY = (RELAY_PLATE_2_ADDRESS, 5)
GATE_VALVE_A_RELAY = (RELAY_PLATE_2_ADDRESS, 6)
GATE_VALVE_B_RELAY = (RELAY_PLATE_2_ADDRESS, 7)
MICROWAVE_COOLING_RELAY = (RELAY_PLATE_2_ADDRESS, 8)

# Esperas del proceso, en segundos
BOOSTER_DELAY_SECONDS = 15
VALVE_SEAT_WAIT_SECONDS = 5
WATER_TANK_RECHECK_SECONDS = 1
REACTOR_WATER_RECHECK_SECONDS = 1
MECHANICAL_PUMP_RECHECK_SECONDS = 1
ROUGHING_PRESSURE_RECHECK_SECONDS = 1
DIFFUSION_TEMPERATURE_RECHECK_SECONDS = 1
FINAL_PRESSURE_RECHECK_SECONDS = 300
MAX_SENSOR_CHECKS = 900

# Límites de las condiciones
MIN_AIR_PRESSURE_PSI = 100.0
MAX_WATER_TANK_TEMPERATURE_C = 10.0
MAX_REACTOR_WATER_TEMPERATURE_C = 10.0
MIN_MECHANICAL_PUMP_TEMPERATURE_C = 37.78
CROSSOVER_VACUUM_TORR = 25e-3
MIN_DIFFUSION_PUMP_TEMPERATURE_C = 177.0

# Valores iniciales y cambios por lectura para la simulación
SIM_INITIAL_AIR_PRESSURE_PSI = 75.0
SIM_AIR_PRESSURE_STEP_PSI = 25.0
SIM_INITIAL_WATER_TANK_TEMPERATURE_C = 24.0
SIM_WATER_TANK_COOLING_STEP_C = 2.0
SIM_INITIAL_REACTOR_WATER_TEMPERATURE_C = 24.0
SIM_REACTOR_WATER_COOLING_STEP_C = 2.0
SIM_INITIAL_MECHANICAL_PUMP_TEMPERATURE_C = 20.0
SIM_MECHANICAL_PUMP_HEATING_STEP_C = 3.0
SIM_INITIAL_CHAMBER_PRESSURE_TORR = 760.0
SIM_ROUGHING_PRESSURE_FACTOR = 0.20
SIM_DIFFUSION_PRESSURE_FACTOR = 0.50
SIM_INITIAL_DIFFUSION_PUMP_A_TEMPERATURE_C = 20.0
SIM_INITIAL_DIFFUSION_PUMP_B_TEMPERATURE_C = 20.0
SIM_DIFFUSION_PUMP_HEATING_STEP_C = 20.0

# Canales reservados para la integración futura de sensores
AIR_PRESSURE_ADC_CHANNEL = 1
CHAMBER_PRESSURE_ADC_CHANNEL = 2
WATER_TANK_THERMO_CHANNEL = 1
REACTOR_WATER_THERMO_CHANNEL = 2
MECHANICAL_PUMP_THERMO_CHANNEL = 3
DIFFUSION_PUMP_A_THERMO_CHANNEL = 4
DIFFUSION_PUMP_B_THERMO_CHANNEL = 5

# Pasos finales sin un relé libre asignado en el diagrama
POWER_SUPPLY_CURRENT_AMPS = 455.0
MICROWAVE_POWER_LEVEL_PERCENT = 50.0
